repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
          - id: check-case-conflict
          - id: check-merge-conflict
          - id: trailing-whitespace
            exclude: .bumpversion.cfg|notebooks/.*\.py
          - id: check-ast
          - id: check-added-large-files
          - id: check-toml
          - id: check-json
          - id: check-yaml

      # PEP 8 compliant opinionated formatter.
    - repo: https://github.com/psf/black
      rev: 23.10.1
      hooks:
          - id: black
            exclude: (docs/|notebooks/){% if cookiecutter.jupytext == "No" %}
          - id: black-jupyter
            files: \.ipynb$

      # Checks Python source files for errors.
    - repo: https://github.com/PyCQA/flake8
      rev: 6.1.0
      hooks:
          - id: flake8
            name: flake8
            entry: flake8
            language: python
            types: [python]
            args: [--config, .flake8]
            exclude: (docs/)

      # Enforces a coding standard, looks for code smells, and can make suggestions about how the code could be refactored.
    - repo: https://github.com/pycqa/pylint
      rev: v3.0.1
      hooks:
          - id: pylint
            exclude: (/test_|tests/|docs/)
            # # You can add additional plugins for pylint here,
            # here is an example for pydantic, remember to enable it in pyproject.toml
            # additional_dependencies:
            #   - 'pylint_pydantic'
            # args:
            #   # pylint can have issue with python libraries based on C
            #   # if it fails to find some objects likely you need to add them
            #   # here:
            #   ["--extension-pkg-whitelist=pydantic"]

